---
title: SP3 Build on OCI
description: Deployment of base SP3 cluster on OCI
schemaVersion: 1.1.0
version: "20210315"
logoUrl: >
  https://objectstorage.uk-london-1.oraclecloud.com/p/gcJUrJ8giUwk_51hi_nTN0Dl66R_7jOOAXU3k3kF-4mOrDCwIoanxChzle0ZAIfm/n/lrbvkel2wjot/b/images/o/mmmlogo_small_130_130.png
locale: "en"
variableGroups:
  - title: "Base configuration"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}
      - ${randomise_ad}
      - ${ad}
      - ${ssh_pub_key}
      - ${env_name}
      - ${specify_prefix}
      - ${name_prefix}
  - title: "Bastion Config"
    variables:
      - ${bastion_image}
      - ${bastion_shape}
      - ${bastion_ocpus}
      - ${bastion_ram}
  - title: "Head Node Config"
    variables:
      - ${headnode_image}
      - ${headnode_shape}
      - ${headnode_ocpus}
      - ${headnode_ram}
  - title: "Worker Config"
    variables:
      - ${select_cust_worker_img}
      - ${custom_worker_img}
      - ${worker_image}
      - ${worker_shape}
      - ${worker_ocpus}
      - ${worker_ram}
      - ${worker_min}
      - ${worker_max}
      - ${worker_use_scratch}
  - title: "Optional Settings"
    variables:
      - ${hn_boot_size}
      - ${hn_data_size}
      - ${hn_work_size}
      - ${use_hp_vol}
      - ${create_child_comp}
      - ${deploy_1k}
      - ${install_certs}
      - ${create_dns}
      - ${show_testing_others}
  - title: "Testing / Other Settings"
    variables:
      - ${bastion_boot_size}
      - ${deploy_test}
    visible: ${show_testing_others}
variables:
  tenancy_ocid:
    visible: false
    type: string
  region:
    title: "Region"
    type: oci:identity:region:name
  compartment_ocid:
    title: "Target Compartment"
    type: oci:identity:compartment:id
    required: true
  randomise_ad:
    type: boolean
    title: "Select random Availability Domain for cluster"
    description: "All nodes for this cluster and the Bastion will be placed in the same, randomly selected AD."
    default: true
  ad:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Availability Domain"
    title: "Availability Domain"
    visible: 
      not:
        - ${randomise_ad} 
  ssh_pub_key:
    type: oci:core:ssh:publickey
    title: "Public SSH key"
    required: true
    additionalProps:
      allowMultiple: true
  bastion_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
      operatingSystem: "Canonical Ubuntu"
      operatingSystemVersion: "18.04"
    required: true
    description: "Compute image for the Bastion server"
    title: "Bastion Server Image"
  bastion_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${bastion_image}
    required: true
    description: "Compute shape for the Bastion server"
    title: "Bastion Server Shape"
  bastion_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    required: true
    title: "Bastion number of CPUs (cores)"
    description: "You can customize the number of CPU cores to a flexible shape."
    visible:
      and:
        - eq:
          - bastion_shape 
          - "VM.Standard.E3.Flex"
  bastion_ram:
    type: integer
    minimum: 1
    maximum: 1024
    required: true
    title: "Bastion Server memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - eq:
          - bastion_shape 
          - "VM.Standard.E3.Flex"
  headnode_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
      operatingSystem: "Canonical Ubuntu"
      operatingSystemVersion: "18.04"
    required: true
    description: "Compute image for the Head Node server"
    title: "Head Node Server Image"
  headnode_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${headnode_image}
    required: true
    description: "Compute shape for the Head Node"
    title: "Head Node Server Shape"
  headnode_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    required: true
    title: "Head Node number of CPUs (cores)"
    description: "You can customize the number of CPU cores to a flexible shape."
    visible:
      and:
        - eq:
          - headnode_shape 
          - "VM.Standard.E3.Flex"
  headnode_ram:
    type: integer
    minimum: 1
    maximum: 1024
    required: true
    title: "Head Node memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - eq:
          - headnode_shape 
          - "VM.Standard.E3.Flex"
  select_cust_worker_img:
    title: "Specify a custom image ID for worker node?"
    description: "Check this box to specify an image ID rather than select from the image list"
    type: boolean
    visible: true
  custom_worker_img:
    title: "Custom image OCID"
    description: "Specify an image OCID here to use, for example, a custom image for the worker nodes in this cluster"
    type: string
    visible: ${select_cust_worker_img}
  worker_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
      operatingSystem: "Canonical Ubuntu"
      operatingSystemVersion: "18.04"
    required: true
    description: "Compute image for the Worker Nodes"
    title: "Worker Nodes Image"
    visible:
      not: 
        - select_cust_worker_img
  worker_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${worker_image}
    required: true
    description: "Compute shape for the Worker Node"
    title: "Worker Node Server Shape"
  worker_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    required: true
    title: "Worker Node number of CPUs (cores)"
    description: "You can customize the number of CPU cores to a flexible shape."
    visible:
      and:
        - eq:
          - worker_shape 
          - "VM.Standard.E3.Flex"
  worker_ram:
    type: integer
    minimum: 1
    maximum: 1024
    required: true
    title: "Worker Node memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - eq:
          - worker_shape 
          - "VM.Standard.E3.Flex"
  worker_min:
    type: integer
    minimum: 0
    maximum: 100
    required: true
    title: "Minimum number of worker nodes"
    description: "Minimum is zero, Maximum 100"
  worker_max:
    type: integer
    minimum: 0
    maximum: 100
    required: true
    title: "Maximum number of worker nodes"
    description: "Maximum is 100 (Minimum 0 - Max must be >= Min"
  worker_use_scratch:
    title: "Worker Node use local scratch storage - choose DenseIO shape"
    type: boolean
    default: false    
  env_name:
    type: string
    title: "Environment Name"
    description: "Name for the environment - e.g. sp3 - lower case and digits only - must start with lower case letter"
    pattern: "^[a-z][a-z0-9]+$"
    default: "sp3"
    required: true
  specify_prefix:
    title: "Would you like to specify a prefix for the deployment?"
    type: boolean
    default: false
  name_prefix:
    type: string
    title: "Display/Host Name Prefix"
    description: "Optional prefix for all Display Names and Hostnames - lower case and digits only - must start with lower case letter"
    pattern: "^[a-z][a-z0-9]+$"
    visible: ${specify_prefix}
  hn_boot_size:
    type: integer
    title: "Head Node Server Boot Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  hn_data_size:
    type: integer
    title: "Head Node Server Data Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  hn_work_size:
    type: integer
    title: "Head Node Server Work Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  use_hp_vol:
    type: boolean
    title: "Use High Performance Block Volumes for /work and /data?"
    description: "Leave this setting ticked to use High Performance Block Volumes.  If unset, Balanced Performance Volumes will be used."
    default: true
  create_child_comp:
    title: "Create a child compartment for the stack"
    type: boolean
    default: true
  install_certs:
    title: "Install sp3dev.ml certificates?"
    type: boolean
    default: true
  create_dns:
    title: "Create DNS record in oci.sp3dev.ml?"
    type: boolean
    default: true
  deploy_1k:
    title: "Deploy the 1000 samples to head node on build?"
    description: "Deploying the 1000 samples to the head node takes 35-40 minutes.  This can be done once the head node is built using the script ~ubuntu/deploy_1k_samples.sh"
    type: boolean
    default: false
  show_testing_others:
    title: "Display all other settings / testing options?"
    type: boolean
    default: false
  bastion_boot_size:
    type: integer
    title: "Bastion Server Boot Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  deploy_test:
    type: boolean
    visible: false
outputs:
  sp3_bastion:
    title: "Bastion Address"
    type: copyableString
    visible: true
  sp3headnodePrivateIP:
    title: "Head Node IP"
    type: copyableString
    visible: true
  sp3_loadbalancer_public_ip:
    type: copyableString
    visible: false
  sp3_deploy_id:
    title: "Deployment ID"
    type: string
    visible: true
  sp3_loadbalancer_url:
    title: "URL"
    type: link
    visible: true
